### ISSUE TITLE
Implement re-try backoff (and eventual timeouts)

### ISSUE THREAD

**Issue by backkem** [pion/dtls#13]
The handshake takes quite some time now. Maybe we can trigger the TimerThread when changing flight?

**Comment by Sean-Der** [comment]
@backkem This was just bothering me the other night, this would be awesome to have. We should kick it again + introduce timeouts. https://tools.ietf.org/html/rfc6347#section-4.2.4

The timeThread should double every time, so we don't just spam every second. (1 -> 2 -> 4)

**Comment by backkem** [comment]
I added an initial implementation in cbdebe94302bdde0a16e18d78ff5ef274430ed89.

**Comment by Sean-Der** [comment]
The handshake now needs to implement backoff mentioned in https://github.com/pions/dtls/issues/13#issuecomment-442248175

But the speed itself is A+ :)

**Comment by Sean-Der** [comment]
@RyanGordon actually I agree with closing this. With DTLS you are supposed to grow the time you send each packet (1 -> 2 -> 4 -> 8)

but IMO I am not that excited to add the complexity/possibility of bugs. I think adding the timeout is perfect as it.

thanks for doing this
