### ISSUE TITLE
ChangeCipherSpec is not decrypted/authenticated

### ISSUE THREAD

**Issue by kixelated** [pion/dtls#138]
Hello, I noticed that there's a special case that exempts `ChangeCipherSpec` from decryption. This is true for every cipher.

https://github.com/pion/dtls/blob/77fae27e533bb08a75644fd6e92a71de9df4d619/crypto_cbc.go#L99

The act of decryption also performs authentication. Without this, attackers can forge and send ChangeCipherSpec packets even when a connection is otherwise encrypted and authenticated.

Today, these packets would be able to kill a connection by bumping the epoch. This can be done blindly by sending a packet to each UDP port, although ICE and connection mapping would make it harder (requires spoofed addresses).

There may be future ramifications and there's no reason to not decrypt/authenticate these packets.

**Comment by Sean-Der** [comment]
Thanks for the report @kixelated !

How does bumping the epoch effect the connection? The remote epoch is only taken into account if we need to replay the initial handshake.

**Comment by Sean-Der** [comment]
I am all for authenticating these though, but since they occur in epoch 0 they all can’t be authenticated. Need to confirm

**Comment by kixelated** [comment]
Yeah, it's probably fine with the current pion implementation. You should really reject ChangeCipherRecord packets unless you're in the right flight of the handshake.

```
   Note that because DTLS records may be reordered, a record from epoch
   1 may be received after epoch 2 has begun.  In general,
   implementations SHOULD discard packets from earlier epochs, but if
   packet loss causes noticeable problems they MAY choose to retain
   keying material from previous epochs for up to the default MSL
   specified for TCP [TCP] to allow for packet reordering.  (Note that
   the intention here is that implementors use the current guidance from
   the IETF for MSL, not that they attempt to interrogate the MSL that
   the system TCP stack is using.)  Until the handshake has completed,
   implementations MUST accept packets from the old epoch.
```

**Comment by Sean-Der** [comment]
Closing since ChangeCipherSpec isn't meant to be encrypted (last packet sent before encryption)

The lack of a state machine (and us handling packets out of order) is a concern though, I am going to create some other tickets for this!
