### ISSUE TITLE
DTLS listener should fail immediately on invalid configuration

### ISSUE THREAD

**Issue by hjames9** [pion/dtls#139]
This is related to an issue I had using DTLS mode in the go-coap library (https://github.com/go-ocf/go-coap/issues/69).  If I attempt to instantiate a DTLS listener, with an invalid configuration (in my case attempting to use an RSA key), the listener will start successfully, but all incoming messages will fail.

### What did you expect?
If provided an invalid DTLS config object, the listener should return an error object with details on the configuration failure.

### What happened?
The DTLS listener successfully started, but all messages on the session fail

I've added a PR with the above changes.  Please review and let me know if it makes sense.
https://github.com/pion/dtls/pull/140
Thanks!

**Comment by daenney** [comment]
I might be missing something but I'm not seeing a PR?

**Comment by hjames9** [comment]
@daenney Attached it to the ticket, had some connection issues but should be available now.

**Comment by Sean-Der** [comment]
Fantastic work @hjames9 

@daenney and @rumpelsepp you both really rock, thank you so much for reviewing stuff and taking time out to make stuff better :)

**Comment by Sean-Der** [comment]
@hjames9 not super urgent, but if you are looking to contribute it would be awesome to remove some of the duplication around config parsing! `Client` and `Server` both have checks we might be able to move into validate.

Also we do have some duplicate testing for `errPSKAndCertificate` and `errIdentityNoPSK` might be nice to pull those out of `conn_test` and simplify that a bit.

thanks! no rush, and totally understand if you don't have the bandwidth :)

**Comment by hjames9** [comment]
@Sean-Der Thanks Sean, I'll take a look at some of this and come back if I have questions.

Thanks @daenney and @rumpelsepp for spending the time on the review

**Comment by hjames9** [comment]
@Sean-Der Would you be able to create a new version tag (1.5.4?) with this change?  I'd like to incorporate the change into go-coap.  Thanks!

**Comment by Sean-Der** [comment]
@hjames9 done!

I am going to work on getting #99 into a `v2` branch now (which will eventually become master and our `v2.0.0`)

@daenney @rumpelsepp we can take this conversation else where, but do you have any changes that break the public API you would like to do? I am in no rush, but would be great to get #99 into master and only break people once.

**Comment by daenney** [comment]
@Sean-Der I've spawned #147 to have that convo instead!
