### ISSUE TITLE
Bring us closer to crypto/tls

### ISSUE THREAD

**Issue by daenney** [pion/dtls#148]
As part of v2 I'd like us to take some time and see if there's more of crypto/tls we can reuse. Mostly want to ensure we don't diverge from interafces and behaviour in crypto/tls unless mandated by the DTLS RFCs. This should help newcomers to immediately get started with pion/dtls as it's hopefully just swapping out crypto/tls for pion/dtls.

**Comment by at-wat** [comment]
I have take a look around `crypto/tls`.
Followings are my suggestion to make `pion/dtls` closer to `crypto/tls`

## Unexpose or move non-DTLS things
### type Closer
It is a package internal utility. It would be better to be unexposed.

### func GenerateSelfSigned(), func SelfSign()
They are for testing and not DTLS specific. It would be better to be unexposed or moved it to somewhere.

### func Fingerprint()
It looks be a part of SDP more than DTLS. Moving it to `pion/sdp` would be better.

## Interfacing
### type Listener
`type Listener` would better be implement `net.Listener`.
`Close(shutdownTimeout time.Duration)` differs from `net.Listener`. Putting `shutdownTimeout` in `Config` struct looks better.

## Misc.
### Clean-up connection timeout config interface
In `crypto/tls`, TCP connection timeout is configured via `Timeout` field in `net.Dialer`. I think adding `dtls.DialWithDialer()` which is compatible with `tls.DialWithDialer()` and making default dialer having 30 seconds of default timeout would be clean and good at compatibility with `crypto/tls`.

**Comment by at-wat** [comment]
> ### func Fingerprint()

Maybe better to move `Fingerprint` and also `HashAlgorithm` under `pkg/crypto`?

**Comment by at-wat** [comment]
## Behavior
### type Listener (#181) ✅ 
- Accepted connections should be available after `Listener.Close()`.

### type Conn (#184) ✅
Pass `nettest.ConnTest`.
- `Read` should return already buffered data even after the connection is closed.
- `SetDeadline` should be implemented.

**Comment by at-wat** [comment]
@daenney @rumpelsepp @jkralik @Sean-Der I have created some PRs to make public APIs more closer to `crypto/tls`. Please add comments if you have any ideas on them.

**Comment by daenney** [comment]
I noticed something in the Go 1.14 releases:

* [ ]: The new CipherSuites and InsecureCipherSuites functions return a list of currently implemented cipher suites
* [ ]: The new CipherSuiteName function returns a name for a cipher suite ID

Might be nice if we provide these too. `CipherSuiteName()` can be implemented by calling `CipherSuite.String()`, since we already have that one.

CipherSuites and InsecureCipherSuites should return a `tls.CipherSuite` which is a bit different from our `dtls.cipherSuite`. It should be easy to map to those though:

```
type CipherSuite struct {
    ID   uint16
    Name string

    // Supported versions is the list of TLS protocol versions that can
    // negotiate this cipher suite.
    SupportedVersions []uint16

    // Insecure is true if the cipher suite has known security issues
    // due to its primitives, design, or implementation.
    Insecure bool
}
```

```
type cipherSuite interface {
	String() string
	ID() CipherSuiteID
	certificateType() clientCertificateType
	hashFunc() func() hash.Hash
	isPSK() bool
	isInitialized() bool

	// Generate the internal encryption state
	init(masterSecret, clientRandom, serverRandom []byte, isClient bool) error

	encrypt(pkt *recordLayer, raw []byte) ([]byte, error)
	decrypt(in []byte) ([]byte, error)
}
```

**Comment by at-wat** [comment]
I think this has been landed, isn't it?

**Comment by daenney** [comment]
Sure looks like it :tada:.

**Comment by at-wat** [comment]
:tada:
