### ISSUE TITLE
Investigate Heartbeat

### ISSUE THREAD

**Issue by backkem** [pion/dtls#15]
Can we guard against badly behaving peers (E.g.: Not sending close_notify) using a Heartbeat? Maybe something like [RFC6520](https://tools.ietf.org/html/rfc6520)?

**Comment by Sean-Der** [comment]
Hey @backkem 

Feel free to re-open, but I don't know if the value is worth the effort. After heartbleed happened this was pulled from LibreSSL (so not supported everywhere)

It also seems like most people just run other things over DTLS, and do health checks their. Feel free to re-open if you disagree.
