### ISSUE TITLE
Adding Basic I/O abstraction

### ISSUE THREAD

**Issue by TetraSomia** [pion/dtls#150]
## Summary

Adding a BIO (Basic I/O abstraction) data structure in order to provide custom read and write callbacks. Those callbacks would be called in `conn.go`.

## Motivation

This would allow users to perform DTLS operations over other IO than the default Network Socket (from `x/net`). We can mention alternatives such as files, memory buffers, or a custom UDP/IP stack implementation.

## Describe alternatives you've considered

An alternative would be to fork this library in order to replace `x/net` types and calls by the desired ones (or to use openssl with cgo 🙃).

## Additional context

Example of DTLS libraries (written in C) that implement this feature:
- [OpenSSL](https://www.openssl.org/docs/man1.1.0/man3/bio.html) with `SSL_set_bio()`
- [MBedTLS](https://tls.mbed.org/kb/how-to/how-do-i-port-mbed-tls-to-a-new-environment-OS) with `mbedtls_ssl_set_bio()`

**Comment by daenney** [comment]
What's the purpose/use case of applying DTLS to files or in-memory buffers? DTLS's whole thing is TLS for datagram transports. Introducing an abstraction to support non-datagram transports doesn't seem all that useful and a potential source of complexity.

If one wants to apply TLS to files or in-memory buffers, both of which are stream oriented "transports", why not use `crypto/tls`?

**Comment by TetraSomia** [comment]
Hello, you're right, I was mentioning cases from the openssl wiki, the personal reason for this request is because I'm using an IOT custom UDP/IP stack that does not provide Berkeley sockets.

**Comment by backkem** [comment]
You can already do this. In construction of a `dtls.Conn` you can provide the `nextConn`. This `nextConn` is a `net.Conn`. You can therefore layer the dtls implementation on top of any `net.Conn` implementation, including `net.UDPConn` (or `ice.Conn` in case of pion/webrtc). The [dial](https://github.com/pion/dtls/blob/master/examples/dial/main.go) and [listen](https://github.com/pion/dtls/blob/master/examples/listen/main.go) examples show how to do this for UDP.
The `net.Conn` is an extension of the `io.ReadWriter` interface. If you wanted you could make a file based implementation as well. You can wrap an `os.File` and mock the rest of the `net.Conn` interface.

**Comment by TetraSomia** [comment]
Oh exact my bad! Thanks a lot for the answers and help.
