### ISSUE TITLE
Improve error handling to be more inline with `crypto/tls`

### ISSUE THREAD

**Issue by Sean-Der** [pion/dtls#163]
Our error handling is causing flakey test runs for `pion/dtls`. The output from `Conn.Close()` isn't consistent between runs, because internally we have racey behavior for setting the global error.

#### Current Behavior
We have one global error `connErr`, every time we have any kind of error. This `connErr` is then polled when doing a `Read`/`Write`/`Close`

This is an issue because `Close` could succeed, but it would return an error because a `Read` had failed (causing `connErr` to be set)

#### New Behavior (Still needs review)
We will have a distinct errors for `readErr`/`writeErr`/`closeErr`

* Calling `Read` will check `readErr` -> `closeErr` then may continue
* Calling `Write` will check `writeErr` -> `closeErr` then may continue
* Calling `Close` will check `closeErr` then may continue
* Failing the handshake will set the `closeErr`

**Comment by Sean-Der** [comment]
@daenney @at-wat What do you think of this? I can try to explain more if anything still needs work, this is causing big problems across all of the `pion/webrtc` tests for a while now.

**Comment by Sean-Der** [comment]
HUGE thank you to @at-wat for figuring out this issue, really impressive that you dug into this and figure it out. I don't think I could have gotten to the bottom of it like you did.

**Comment by at-wat** [comment]
@Sean-Der thanks!

I roughly read `crypto/tls/conn.go`.
How about the following?:

- Failing the handshake will set `handshakeErr`
- Calling `Read` will
  1. check `handshakeErr` and return it if non `nil`
  2. check connection and return `io.EOF` if closed
  3. check `readErr` and return it if non `nil`
- Calling `Write` will
  1. check connection and return `ErrClosed` if closed
  2. check `handshakeErr` and return it if non `nil`
  3. check `writeErr` and return it if non `nil`
- Calling `Close` will
  1. close the connection and return error from `nextConn.Close()`

**Comment by daenney** [comment]
@Sean-Der Makes a lot of sense to me, and I like the idea of splitting these errors out. Have one error entity be responsible for all kinds of different errors is usually problematic, and tends to make code that needs to know what type of error it really is quite messy to write.

What @at-wat is proposing sounds sensible to me. What I don't understand is why on `Write` a closed connection should return `ErrClosed` but on Read it's suggested we return `io.EOF`. That seems inconsistent and potentially confusing?

The other thing I'm wondering about is if the handshake fails shouldn't we close the connection on our side? In that case we would only check if the connection is closed, and if so return why, (ErrHandshake in the case the handshake failed, ErrClosed if we explicitly called Close, or something along those lines)

**Comment by at-wat** [comment]
@daenney I think making behaviour as same as possible with `crypto/tls` may be one of the way to reduce confusion. In `crypto/tls`, `Conn.Read` looks returning `io.EOF` on close and `Conn.Write` returns `TCPConn` return values directly.
https://github.com/golang/go/blob/0377f061687771eddfe8de78d6c40e17d6b21a39/src/crypto/tls/conn.go#L1245-L1257
But, yes, we can change it to improve usability.

**Comment by daenney** [comment]
That's a fair point, I hadn't seen that bit in crypto/tls yet.

**Comment by Sean-Der** [comment]
Have made some decent progress, but hit some annoyances.

* We should just drop the `inboundLoop`, then we can just return read errors right back to the user
I don't know how to do this yet, but we should investigate it. This also would remove a whole copy + routine. 

* `net.Pipe` makes it hard to test
When one side closes the other side gets an `io.EOF` I need to write some sort of shim so each side needs to call close.

https://github.com/pion/dtls/commit/0574041e277782e44255566d1d95e765aaf73713 is my first stab. Calling it a night, if anyone wants to join in feel free to push right to that branch! I will not be able to work on it for ~12 hours.

I might not be going down the right path, feel free to rewrite everything if anyone wants to get involved!

**Comment by at-wat** [comment]
> `net.Pipe` makes it hard to test

I'll add one for this.

**Comment by Sean-Der** [comment]
Ok the first part landed, step in the right direction but still needs some work!

I am going to continue work on
* Remove `inboundLoop`, we should only read packets when `Read()` is called. This will reduce a lot of complexity.
* Add tests that assert `Read`/`Write`/`Close` behave as expected.

**Comment by at-wat** [comment]
Read/Write behavior after the error and Close is now compatible with net.Conn. (https://github.com/pion/dtls/pull/184) (https://github.com/pion/dtls/pull/184)

**Comment by daenney** [comment]
I'm going to go ahead and close this, just to clean up the issue tracker a bit. @Sean-Der if you feel we missed something as part of #184 go ahead and re-open it.
