### ISSUE TITLE
context.Context based cancellation

### ISSUE THREAD

**Issue by at-wat** [pion/dtls#189]
Proposed at https://github.com/pion/dtls/issues/147.

https://github.com/pion/dtls/issues/147#issuecomment-580080132
> @Sean-Der:
> What do you think of updating Client/Server to take a context? I need a way to be notified that an error has occurred, and it looks like taking a `Context` is the proper way to have a async way to bubble up an error. I talk about it in #151 a bit.

**Comment by at-wat** [comment]
It's also related to https://github.com/pion/dtls/issues/151 and https://github.com/pion/dtls/issues/163#issuecomment-567383197.

One of the related problem of the current `Client()/Server()/Dial()` is that `Conn` is returned before it gets available.
I prefer to make these functions blocking until the DTLS handshake is completed, so that the caller must call it with context with proper timeout or deadline. (Just like that the `DialTCP` returns `Conn` after completing TCP three-way handshaking.)
In this design, we might be able to drop `ConnectTimeout` option and `ConnectTimeoutOption` helper.

The new API could be:
```go
func Dial(ctx context.Context, network string, raddr *net.UDPAddr, config *Config) (*Conn, error) {}

func Client(ctx context.Context, conn net.Conn, config *Config) (*Conn, error) {}

func Server(ctx context.Context, conn net.Conn, config *Config) (*Conn, error) {}
```

**Comment by at-wat** [comment]
Adding `ctx context.Context` makes the API different from `crypto/tls`.
We can also keep the current `Dial/Client/Server` and add `DialWithContext/ClientWithContext/ServerWithContext`.

**Comment by daenney** [comment]
I'd vote for the second option, adding the `WithContext` methods. There's a pretty decent precedent in `net/http` for doing that, and I'd prefer to not have our exported methods that share a name with `crypto/tls` diverge.

**Comment by daenney** [comment]
On `net.Dialer` though you can already pass in a `context`, so perhaps it's not needed?

**Comment by at-wat** [comment]
`Dialer` sounds that is only for `Dial`, but we have to do the same things on `Cilent` and `Server`. And, most of the things in `Dialer` can be provided by `Config`.
So, I think `Dialer` is not very useful for us.

**Comment by at-wat** [comment]
I made a draft PR at #191.

One problem is that `Listener.Accept` internally calls `Server`, but `Accept` can't take `context.Context` as it waits until a new connection is requested from outside.

**Comment by at-wat** [comment]
## To be discussed

### ConnectTimeout config
Having timeout both by `context.Context` and `dtls.Config` is confusing.
However, as `Accept` should internally start connection timeout timer, it can't receive `context.Context`. In addition, listener is an implementation of `net.Listener` now, adding a new method makes it diverged from `tls.Conn`.

### Error value on timeout
Currently, `errConnectTimeout` is returned on timeout, but returning an error that `Is(context.DeadlineExceeded)` would be better.
ref: https://github.com/golang/go/issues/31449

**Comment by at-wat** [comment]
> ### ConnectTimeout config

Adding a
```go
	// function to make a context used in Dial(), Client(), Server(), and Accept().
	// If it is nil, default context with 30s timeout is used.
	ConnectContextMaker func() (context.Context, func())
```
to `dtls.Config` and doing
```go
	ctxParent, cancelParent := context.WithCancel(context.Background())
	defer cancelParent()

	config := &dtls.Config{
		ConnectContextMaker func() (context.Context, func()) {
			return context.WithTimeout(ctxParent, 30*time.Second)
		},
	}
	listener, err := dtls.Listen("udp", addr, config)
	conn, err := listener.Accept()
```
```go
func (l *listener) Accept() (net.Conn, error) {
	c, err := l.parent.Accept()
	if err != nil {
		return nil, err
	}
	ctx, cancel := l.config.ConnectContextMaker()
	defer cancel()
	return ServerWithContext(ctx, c, l.config)
}
```
allows to Inherit the parent context to `listener.Accept()` internal context.

**Comment by at-wat** [comment]
@daenney @Sean-Der how do you think these APIs?
