### ISSUE TITLE
Respond to close_notify with close_notify

### ISSUE THREAD

**Issue by at-wat** [pion/dtls#197]
https://tools.ietf.org/html/rfc5246#section-7.2.1
>   ```
>   Unless some other fatal alert has been transmitted, each party is
>   required to send a close_notify alert before closing the write side
>   of the connection.  The other party MUST respond with a close_notify
>   alert of its own and close down the connection immediately,
>   discarding any pending writes.  It is not required for the initiator
>   of the close to wait for the responding close_notify alert before
>   closing the read side of the connection.
>   ```

`The other party MUST respond with a close_notify`

https://github.com/pion/dtls/blob/34ebfdba22d430240630610d70edf371d8b121fc/conn.go#L667-L672

**Comment by daenney** [comment]
Maybe we don't need to raise an issue, if you're immediately going to submit a PR to fix it? It causes a lot of noise in my GitHub notifications, so I'm wondering what the thought behind doing this is. The PR itself can also contain all the details?
