### ISSUE TITLE
CCM ciphersuite causes a lot of CPU load

### ISSUE THREAD

**Issue by cohosh** [pion/dtls#199]
### Your environment.
  - Version: v2.1.18
  - Browser: N/A (Snowflake)
  - Other Information: CPU profiling output given below

### What did you do?
We've been running Snowflake with the pion/webrtc library for a while now. We noticed that our Snowflake proxies were using a lot more CPU than expected in sending and receiving WebRTC messages.

More info on snowflake: https://snowflake.torproject.org

### What did you expect?

We expected the CPU usage to be around 10-20% for proxying a single client's traffic.

### What happened?

Our CPU usage for a single client was over 60%.

After some investigations, we tracked a lot of CPU heavy operations coming from the CCM ciphersuite. Changing the ciphersuite to GCM resulted in the more expected usage of 10-20%.

See our ticket here: https://trac.torproject.org/projects/tor/ticket/33211#comment:14

I'd suggest
1) allowing a way for application develoeprs to change the ciphersuite (as filed here: https://github.com/pion/webrtc/issues/1043)

2) taking a look at the CCM implementation to see if there are some optimizations available there, and

3) using a different default ciphersuite and update the priority listing of available ciphersuites. GCM is supposed to be slightly more efficient, and is much more commonly seen in practice.

**Comment by Sean-Der** [comment]
My guess is [this list](https://github.com/pion/dtls/blob/master/cipher_suite.go#L116) is used backwards, and we are preferring the wrong CipherSuites. 

I will look into that, and make sure we get a test in. Thanks for filing this @cohosh! I doubt we will ever get close to beating GCM Go, the stdlib use AES-NI and has a bunch of scrutiny :)

**Comment by cohosh** [comment]
Yep, that seems plausible. This is pion-to-pion traffic so the ciphersuite used **should** be the highest priority one listed there.

**Comment by cohosh** [comment]
It could also be that [https://github.com/pion/dtls/blob/master/cipher_suite.go#L127](this list of all cipher suites) is being used instead.

**Comment by Sean-Der** [comment]
@cohosh Fixed! Mind reviewing that PR, I will merge + tag across.

**Comment by Sean-Der** [comment]
![Screen Shot 2020-02-21 at 2 26 26 PM](https://user-images.githubusercontent.com/1302304/75076978-50869600-54b6-11ea-8607-a246340531f0.png)

**Comment by Sean-Der** [comment]
@daenney @at-wat @igolaizola @cohosh I also have moved GCM above CBC. I wanted to add everyone, this feels like something we should have consensus on.

My motivation is
* Matches Chromium/FireFox
* In most cases will be faster for users

I have attached a screenshot above showing Chromium Nightly's current values.

**Comment by cohosh** [comment]
Nice, thanks @Sean-Der ! I'll take a look at this and get back to you later tonight.

**Comment by daenney** [comment]
CCM should really not have been advertised or picked by default at all. That was only added in DTLS in order to support some IoT use-cases, b/c among other things the CoAP RFC requires it.

@Sean-Der I'd vote we add a second change, dropping any CCM suite from the defaults.

**Comment by daenney** [comment]
W.r.t optimising CCM, that's not really been undertaken yet b/c it would probably mean having to drop down to assembly. That's a maintenance burden and potential massive source of security issues I don't want to incur just yet.

**Comment by cohosh** [comment]
Thanks for taking care of this, the changes solve the issue we were having at our end :)

**Comment by Sean-Der** [comment]
@daenney done! opened PR and added you as @jkralik as reviewer.
