### ISSUE TITLE
Refactor handshake state machine

### ISSUE THREAD

**Issue by at-wat** [pion/dtls#205]
ref: https://github.com/pion/dtls/issues/143

- Implement DTLS Timeout and Retransmission State Machine as specified in https://tools.ietf.org/html/rfc6347#page-22
  - Fix retransmission conditions
  - FIx handshake exit condition
- Refactor incoming handshake packet handling
  - Split all-in-one function to per-state function/interfaces

**Comment by at-wat** [comment]
Implementation of the state machine described in https://tools.ietf.org/html/rfc6347#page-22 is almost done. I'll open PR within a few days.

**Comment by Sean-Der** [comment]
That's fantastic news @at-wat! The code base totally grew organically, so excited to see that get cleaned up :)
