### ISSUE TITLE
undefined: curve25519.X25519

### ISSUE THREAD

**Issue by genofire** [pion/dtls#228]
go version go1.14 linux/amd64

src/github.com/pion/dtls/prf.go:72:10: undefined: curve25519.X25519

**Comment by daenney** [comment]
Something seems weird with your build. curve25519.X22519 is defined in https://godoc.org/golang.org/x/crypto/curve25519, which we import, and is part of x/crypto that's in go.mod.

**Comment by daenney** [comment]
The version of x/crypto we use is at commit `2aa609cf4a9d`, which has the `X25519` method: https://github.com/golang/crypto/blob/2aa609cf4a9d7d1126360de73b55b6002f9e052a/curve25519/curve25519.go#L67

**Comment by genofire** [comment]
ups, sry - ` go mod download` helps
... you still keep it in mind on updating dependencies?
