### ISSUE TITLE
When multi UDP request comming, The Server will crash

### ISSUE THREAD

**Issue by wk331100** [pion/dtls#234]
### Your environment.
  - Version:  The latest Pion\dtls
  - Server:  Centos7
  - Test command: nc -nvz -u 127.0.0.1 4444  form Centos 6.5
 

### What did you do?

Run the Server from examles/listen/main.go.   when run the command ` nc -nvz -u 127.0.0.1 4444`, The Server crashed.  I have add `continue` in listen/main.go.  run `nc`  agin , The server cannot be connected by other correct client any more.

### What did you expect?

Just As a Web server . The correct request comes , the program do what should do . But the request with not dtls package , just note the error 。Let the correct connect request can run all the time。

Thanks, If This problem can be fixed in time. I can use it in my project.

**Comment by at-wat** [comment]
This seems a bug of the example.

```diff
diff --git a/examples/listen/main.go b/examples/listen/main.go
index d3ad255..1d812be 100644
--- a/examples/listen/main.go
+++ b/examples/listen/main.go
@@ -62,7 +62,9 @@ func main() {
                        // functions like `RemoteCertificate` etc.
 
                        // Register the connection with the chat hub
-                       hub.Register(conn)
+                       if err == nil {
+                               hub.Register(conn)
+                       }
                }
        }()
```
should be correct.

**Comment by at-wat** [comment]
@wk331100 Now the example on master branch is fixed. Feel free to reopen if the problem still exist.
