### ISSUE TITLE
Support both PKI and PSK (at the same time)

### ISSUE THREAD

**Issue by jdbruijn** [pion/dtls#297]
## Summary

I'd like to use both PKI and PSK as a DTLS server, for different clients. So one client makes a connection and uses PKI and another client makes a connection and uses PSK. As these are different 'instances', so to speak, I don't see why this wouldn't be possible. I've seen in the config validation, `validateConfig` that it will give an error on `len(config.Certificates) > 0 && config.PSK != nil`, so I know that that would be blocking supporting both for now. What I don't know and am curious to hear about, is whether the underlying code would work with supporting both or whether that change would be a difficult one.

https://github.com/pion/dtls/blob/master/config.go#L157-L158
```go
func validateConfig(config *Config) error {
	switch {
	case config == nil:
		return errNoConfigProvided
	case len(config.Certificates) > 0 && config.PSK != nil:
		return errPSKAndCertificate
	case config.PSKIdentityHint != nil && config.PSK == nil:
		return errIdentityNoPSK
	}
```

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome? Is this available in other implementations? Can this not be implemented using primitives?
Reason for this is to support different types of clients from one server. We currently have one server that can serve N clients concurrently but that now only handles PKI. We want to have devices connecting to the server using both PKI and PSK.

## Describe alternatives you've considered

A clear and concise description of the alternative solutions you've considered.
One alternative would be to have a load balancer and multiple servers, some for PKI and some for PSK. The load balancer would then of course need to figure out what the client wants to do, PKI or PSK, and pass to the appropriate server. This alternative would be quite complex for us to implement and be a less 'clean' solution IMO.

**Comment by daenney** [comment]
Is there any prior art for a TLS server that accepts both for the same host:port tuple? I'm not aware of such a thing in the wild, even though theoretically it's possible. I can't get something like stunnel to support both at the same time, for example.

For PSK to provide any real value, you'd need to know the clients upfront, and configure each one with a different key. Otherwise it's just one big shared password which seems rather dangerous, and a compromise of that password would compromise every single client using PSK.

I would be inclined to start two different servers, `:portX` for PKI, `:portY` for PSK. That also makes it easy to split out the traffic and have a smaller/larger pool for each depending on the usage.

**Comment by jdbruijn** [comment]
Thanks for your feedback. I have not seen it in the wild either but thought, why not? If it is at least somewhat easy (like don't have to change a > 5% part of the code base) to implement, I think it would be a nice feature. Do you have any idea whether that is the case or requires a lot more changes?

> For PSK to provide any real value, you'd need to know the clients upfront, and configure each one with a different key. 

In this case each client will get its own key and the server, which is using pion/dtls, will get the specific key from another server so it adds some real value. I know it is less secure than PKI, but in some cases that is simply not possible due to hardware or connectivity restrictions.

**Comment by daenney** [comment]
> I have not seen it in the wild either but thought, why not? 

I don't know. I do think it's feasible. But the fact that nobody else seems to support it does have me wondering whether we're missing something that makes doing this undesirable, or if it's just inertia/nobody else has had the need.
