### ISSUE TITLE
Implement TLS_ECDH_ANON_WITH_AES_128_CBC_SHA256

### ISSUE THREAD

**Issue by Sean-Der** [pion/dtls#337]
I am going to take the work @jkralik has already done into master. 

The existing code is on this branch https://github.com/pion/dtls/tree/cipherSuiteFactory. The in a follow up PR I am going to add the `CipherSuiteFactory` to the config that allows people to pass anything that satisfies `dtls.CipherSuite`

**Comment by daenney** [comment]
That sounds good. I'm happy with a generic mechanism that lets people use any/custom cipher suites (i.e stuff we don't need to implement ourselves) but I'd like to avoid explicitly supporting TLS_*_ANON_* ciphers in this library. Since that results in a connection where neither server or user it authenticated it's trivially MITMable.

**Comment by jkralik** [comment]
@daenney Our library https://github.com/plgd-dev/sdk implements specification https://openconnectivity.org/specs/OCF_Security_Specification.pdf where ANON is used for Just-Works owenrship transfer method) (section 7.3.4.1). I understand your concerns, but we want to stick to the specifications.

**Comment by daenney** [comment]
Ya no, absolutely. I should've said export instead of support. I'm fine with us having a facility for it, but I'd rather not carry ANON ciphers in this library itself.

**Comment by Sean-Der** [comment]
@daenney Totally agree, these are my motivations (and plans) hopefully this works for everyone 

* We don't want forks. Lose out on good feedback/contributions
* Don't encourage insecure configurations/ship the least amount of code possible.

----

What do you both think of the following

* Export `CipherSuite` and allow users to pass their own via `CipherSuiteFactory`
* Add `IsAnonymous` to `CipherSuite`, only usable if a user passes their own via `CipherSuiteFactory`
* Move the following to `pkg`. `newCryptoCBC`, `prfEncryptionKeys`. 


You won't have an easy `CipherSuite Constructor`, but I am just worried about having multiple entry points.

**Comment by jkralik** [comment]
@Sean-Der I'm ok with that. If I am able to put my ANON to CipherSuiteFactory then it is ok. Maybe one think: How we need to test ANON ciphers ?

**Comment by Sean-Der** [comment]
Ok we are getting closer! I have made all the Ciphers/Protocol public. I just need to add the config option, and add anon ciphers.

https://gist.github.com/b469998a12facee778e9726b6f708129 is the changes from @jkralik patch and just need to get them in.

**Comment by Sean-Der** [comment]
@jkralik Should we tag a new version? Everything seems to work?

**Comment by jkralik** [comment]
@Sean-Der Sure. It works perfect.
