### ISSUE TITLE
Add flag to disable SNI

### ISSUE THREAD

**Issue by kegsay** [pion/dtls#345]
## Summary

Currently, the library will [always](https://github.com/pion/dtls/blob/v2.0.5/conn.go#L150) send the `server_name` extension even if `config.ServerName` is blank. I feel this is correct behaviour, but it should be possible to opt-out of this behaviour.

## Motivation

I would like this for two main reasons:
 - Supporting extreme low bandwidth use cases where the SNI extension adds precious bytes to the `ClientHello`.
 - Privacy, as [leaking the SNI](https://en.wikipedia.org/wiki/Server_Name_Indication#Security_implications) has known tradeoffs.

## Proposal

Add `config.DisableSNI` which by default is `false`. If `true`, [this check is false](https://github.com/pion/dtls/blob/v2.0.5/conn.go#L151). This would mean explicitly setting `config.ServerName` will still send the `server_name` extension, but passively leaving it blank will stop it being sent.

**Comment by Sean-Der** [comment]
What does `crypto/TLS` do? Do they send if ServerName is blank? 

IMO we should match. They have made really great decisions so following upstream is 👍 From me

**Comment by Sean-Der** [comment]
Fixed by 8f0a63079a965465ea09a7922404ee8e6325f3bf

When serverName is empty the SNI isn't sent. Thank you for fixing this @cohosh !
