### ISSUE TITLE
Support for GetCertificate and GetClientCertificate similar as in crypto/tls

### ISSUE THREAD

**Issue by zllovesuki** [pion/dtls#386]
## Summary

Go's `crypto/tls` has support for `GetCertificate` where it can return a certificate used for the handshake based on ClientHello. Though this feature is commonly used to issue ACME certificate on the fly, or to support certificate reloading without restarting the server.

## Motivation

It would be tremendously useful to support `GetCertificate` in dtls so the server doesn't have to have the certificates issued already on start-up, and closes the features parity between `crypto/tls` and `dtls` where it can almost be a drop in replacement, at least for the use cases outline above.

## Describe alternatives you've considered

I'm not aware of any workaround for this feature, though I admit that I haven't dug into the code too deeply.

## Additional context

`nil`

**Comment by Sean-Der** [comment]
Hey @zllovesuki 

That sounds great to me! Anything that matches `crypto/tls` I am in support of. If you have any questions about implementing happy to help, I am also in [Slack](https://pion.ly/slack)
