### ISSUE TITLE
when call conn.Read()  got error read: message too long

### ISSUE THREAD

**Issue by polevpn** [pion/dtls#425]
`
when call conn.Read() 
get the following error
dtls fatal: read udp xxx.xx.xx.xx:48859->xx.xxx.xx.xxx:8443: read: message too long,actually writing buffer size less than 2k
`

### Your environment.
  - Version: v2.1.1
  - Browser: *include version*
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

**Comment by daenney** [comment]
We need more information on what you were doing and how to reproduce this. Please fill out the issue template properly. As it stands right now we don't have enough information to do anything about this.

**Comment by Sean-Der** [comment]
@polevpn I don't believe this error is from us. That looks like the human readable description for [EMSGSIZE](https://github.com/golang/go/blob/f229e7031a6efb2f23241b5da000c3b3203081d6/src/syscall/zerrors_linux_amd64.go#L1469)

What OS are you using? Are you using UDP? Happy to help, but not a `pion/dtls` issue.
