### ISSUE TITLE
Connection timeout ignores configured context timeout

### ISSUE THREAD

**Issue by nealjack** [pion/dtls#521]
### Your environment.
  - Version: *v2.1.6-0.20230104045405-f40c61d83b5f*
  - Browser: *N/A*
  - go-coap and pion dtls configuration:
```go
        log.Fatal(coap.ListenAndServeDTLS("udp", ":5684", &piondtls.Config{
                PSK: func(hint []byte) ([]byte, error) {
                        fmt.Printf("Client's hint: %s \n", hint)
                        return []byte("secret"), nil
                },
                PSKIdentityHint: []byte("server"),
                CipherSuites:    []piondtls.CipherSuiteID{piondtls.TLS_PSK_WITH_AES_128_CCM_8},
                ConnectContextMaker: func () (context.Context, func()) {
                        return context.WithTimeout(ctx, 5*time.Minute)
                },
        }, m))
```

### What did you do?
Attempting to connect an embedded device to a go coap server using pion dtls. This embedded device transmits infrequently, only once every minute. After every message, the server closes the connection/session due to a handshake timeout. The client must reconnect with a full handshake for every message. Based on the [existing examples](https://github.com/pion/dtls/blob/3dca8e49b7af5c111694e6a386c3568913e3cdbf/examples/listen/psk/main.go#L34) that mention adding a context maker for connection timeouts, I added a context timeout of 5 minutes to the pion dtls configuration, however it does not change the handshake timeout behavior.

### What did you expect?
I expected that using a custom context with a longer timeout of 5 minutes would keep the connection open for five minutes instead of the default 30 seconds.

### What happened?
The handshake timeout occurs about 20 seconds after the handshake "Flight 6: Finished". This is neither the default 30 second timeout nor the 5 minute timeout that I configured.

```
dtls TRACE: 23:32:04.822736 handshaker.go:172: [handshake:server] Flight 6: Finished
<application logging on rx'd packet>
dtls TRACE: 23:32:24.172443 conn.go:902: handshake timeouts - closing underline connection
```

I'm new to both Go and  Pion DTLS, so I could be using the library incorrectly. Please let me know if there is a way to keep connections open for a longer time period!

**Comment by daenney** [comment]
Can you reproduce this issue without go-coap in the mix? I'm not sure what else `coap.ListenAndServeDTLS` may be doing. You should be able to adapt https://github.com/pion/dtls/blob/master/examples/listen/psk/main.go pretty easily to test this.

**Comment by jkralik** [comment]
Based on what I see, you use `coap.ListenAndServeDTLS`, which by default has an InactivityMonitor that closes the connection after 16 seconds.
https://github.com/plgd-dev/go-coap/blob/7f5072879e76a6312fed75c45de17279fe14a7eb/dtls/server/config.go#L30

So could you try create DTLS server similar as in the test with greater timeout? https://github.com/plgd-dev/go-coap/blob/7f5072879e76a6312fed75c45de17279fe14a7eb/dtls/server_test.go#L208 ?

**Comment by nealjack** [comment]
@daenney I am currently trying that, however I can't get the example you mentioned to actually open and serve on my port (5684). It's probably an issue on my end and I'll try to resolve it.

@jkralik Thanks for the suggestion. I did look into that earlier and found that increasing the InactivityMonitor timeout to 5 minutes did not extend the connection length. My client still had to reconnect and do a full handshake for every transmission on a one minute interval.

**Comment by nealjack** [comment]
To clarify, I manually changed the 16 second timeout to a 5 minute one in the default server instantiation by modifying the go coap package. I did not try to create a server as the test does. I can try manually configuring the server instead.

**Comment by nealjack** [comment]
@daenney I got the example to work! I am testing on an EC2 instance and had to change to example to serve on the instance's internal address instead of localhost.

The example DTLS listener does not close the connection like the go-coap one does. So this does appear to be a go-coap issue. Looks like I was barking up the wrong tree, under the flawed assumption that pion dtls was managing the "connection".

Thank you for the suggestions for sanity checking @daenney, and thanks for the suggestion in go-coap, @jkralik. I will keep searching for a fix on the coap side of things and report back in case anyone else eventually has this issue.

**Comment by nealjack** [comment]
@jkralik was right! It is an issue with the default configuration of the go-coap dtls server. By default the `coap.ListenAndServeDTLS` function creates a [new server](https://github.com/plgd-dev/go-coap/blob/b8901963ae43acd9a14f98b3d47ec17b26b38e7a/server.go#L78) with [this configuration](https://github.com/plgd-dev/go-coap/blob/3b5516192627682a2d6be3205c54822167765735/dtls/server/config.go#L27).

To create a server and pass options that are different than default, users should create their own version of `coap.ListenAndServeDTLS` that passes those options in the `dtls.NewServer` call. For example, I implemented my own `listenAndServeDTLSTimeout`:

```go
func listenAndServeDTLSTimeout(network string, addr string, config *piondtls.Config, handler mux.Handler, timeout time.Duration) (err error) {
        l, err := net.NewDTLSListener(network, addr, config)
        if err != nil {
                return err
        }
        defer func() {
                if errC := l.Close(); errC != nil && err == nil {
                        err = errC
                }
        }()

        s := dtls.NewServer(options.WithMux(handler), options.WithInactivityMonitor(timeout, func(cc *udpClient.Conn) { _ = cc.Close() }))
        return s.Serve(l)
}
```

When I pass a timeout of `time.Minute*5` to this function, my server functions and does not close the connection on my client device. Hopefully this helps anyone else that wants to configure their CoAP and DTLS server differently.
