### ISSUE TITLE
when connecting new listener, bind:already in use error occurs

### ISSUE THREAD

**Issue by lhd2001** [pion/dtls#542]
### Your environment.
  - Version:   v.2.0.10, v.2.2.6 *Release or SHA*
  - Browser: golang:1.14-alpine3.12, golang:1.20.3-alpine3.17 *include version*
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*
  listener.go line 70 : return Server(c, l.config)
------------------------------------------------>
    s, err := Server(c, l.config)
    if s == nil {
        c.Close()
    }

    return s, err
}
### What did you do?

After Accept, server (c, l.config) returns nil.
 Later, listener close -> when connecting new listener

### What did you expect?
new listener bind

### What happened?
bind:already in use error occurs.
Because udp.Listen is stopped at l.connWG.wait

**Comment by hasheddan** [comment]
Hi @lhd2001! Are you trying to re-use the underlying UDP listener with a new DTLS listener?

**Comment by Sean-Der** [comment]
Hopefully you got this work @lhd2001!

If you are still having problems we are here to help, thanks for using Pion :)
