### ISSUE TITLE
BadCertificate error on Linux arm64

### ISSUE THREAD

**Issue by hikris007** [pion/dtls#555]
Hello,
I am encountering an issue with the pion/dtls project. The server runs perfectly fine on both Windows and Linux platforms, but when I try to run it on Linux arm64, I get a BadCertificate error.
Here is my setup:

Server: Running on Windows 10
Client: Running on Xiaomi Router AX6 (Linux arm64)

I have thoroughly checked the certificate files and they seem to be in order. Interestingly, when I run the client on Windows 10 with the same parameters and certificate files, it works without any issues.
I am not sure why this is happening. Could it be a compatibility issue with Linux arm64? Any help or guidance would be greatly appreciated.
Thank you.

**Comment by daenney** [comment]
We don't do anything with certificates. Unless you configure them explicitly when creating the client and server, Go will use the certificate stores of each of your platforms.

It would be helpful if you could share the code in question, so we can understand what you're doing.

**Comment by hikris007** [comment]
Here's part of code
<img width="730" alt="截屏2023-07-06 22 04 08" src="https://github.com/pion/dtls/assets/97677690/7af4e178-abab-4562-a8dc-7ebd95015abe">

**Comment by hikris007** [comment]
[func (s *Server) initListener() error {](https://github.com/hikris007/dtls_tunnel/blob/733876c6bfd76a5c94ea5feb5923daa6b4e9e4c0/server.go#L39C5-L39C5)
This is the code

@daenney

**Comment by hikris007** [comment]
I'm really sorry, I changed the client's system time and retry, and found that it worked, sorry to bother you @daenney

**Comment by daenney** [comment]
No worries, these things happen. Glad that was all it was!
