### ISSUE TITLE
TestErrorsTemporary fails with "can't assign requested address"

### ISSUE THREAD

**Issue by enobufs** [pion/dtls#614]
### Your environment.
  - Version: 38e39e4
  - Browser: n/a

### What did you do?
Ran unit tests on my mac:
```
% sw_vers
ProductName:		macOS
ProductVersion:		14.2.1
BuildVersion:		23C71
```

### What did you expect?
All tests under pion/dtls to pass.

### What happened?
```
=== RUN   TestErrorsTemporary
    /Users/ytakeda/Projects/pion/dtls/errors_errno_test.go:26: Unexpected error: dial udp 127.0.0.1:0: connect: can't assign requested address
--- FAIL: TestErrorsTemporary (0.00s)
FAIL
FAIL	github.com/pion/dtls/v2	0.203s
```

**Comment by enobufs** [comment]
@at-wat do you remember what the purpose of this test was? I feel this test should just be removed...

**Comment by daenney** [comment]
That error seems to come from DialUDP. That really should never fail, for something with port 0 as that's just "give me a free port on this machine". The test doesn't fail for me locally, and I've never seen it fail in CI. I don't think we should just scrap the test without understanding what's causing this.

**Comment by at-wat** [comment]
> @at-wat do you remember what the purpose of this test was? I feel this test should just be removed...

This tests `netError()` which wraps raw errors by the typed errors.
https://github.com/pion/dtls/blob/9e8c93ee311499a813046d51bf50ffe5f4df9ad7/errors.go#L79-L99
Raw errors from network operations may have `Temporary()` and `Timeout()` interface which must be inherited to the typed errors.

**Comment by enobufs** [comment]
@at-wat
I see! I did not notice it. So, this test needs to create a case where "connected" (bound to a specific remote transport) UDP socket but the server is not listening, and expecting to receive a TemporaryError from conn.Read.

@daenney 
> That really should never fail, for something with port 0 as that's just "give me a free port on this machine".

That is true for local port in my understanding. I believe the error is about remote port set to 0. "hey, connect me to any port!" does not make sense to me, but it landed on master, it must have passed the test, but not on my mac...

To create the intended setup, I think we should use net.ListenUDP on 127.0.0.1:0, get its local address, then close it right away.  Then, use the address as the remote adder (no one is listening) for the DialUDP...

Thoughts?
