### ISSUE TITLE
Extract MKI from DTLS-SRTP

### ISSUE THREAD

**Issue by sirzooro** [pion/dtls#650]
## Summary

Please extract MKI from DTLS-SRTP and use it if present.

## Motivation

Earlier today I merged my PR to `pion/srtp` package which adds MKI support to SRTP. Now it would be good to add MKI support in other places in pion code. I am not familiar with DTLS protocol, so I decided to open this feature request.

**Comment by Sean-Der** [comment]
I can work on that @sirzooro! I really appreciate everything you have done with srtp lately, happy to grab other things to unblock you :)

I will have a PR by EoW

**Comment by daenney** [comment]
> DTLS-SRTP extension allows to specify MKI for keys. It is sent in `srtp_mki` field of `use_srtp` extension: https://www.rfc-editor.org/rfc/rfc5764#section-4.1.1 . I saw in pion/dtls code that zero-length MKI (i.e. no MKI) is currently supported. I am asking to add support for any MKI.

Ahh, that's why I couldn't find it. I see now. Thanks for the info!
