### ISSUE TITLE
Secondary IP problem

### ISSUE THREAD

**Issue by evangelme** [pion/dtls#658]
i have 2 IPs for a server imagine my IPs are 1.1.1.1 and 2.2.2.2
i want the client to connect to 2.2.2.2:2815 and the server gives the data to client with 1.1.1.1:2815 but the tunnel gives me error because the sender and reviser's IP is not the same. how do you think i should solve this problem. i know it is not the right way to use it but our internet in on censorship and the only way i can use it permanently is this what do you suggest i should do for your DTLS tunnel to accept this connection.
Thank you.

**Comment by Sean-Der** [comment]
Hi @evangelme 

Is it possible to open the UDP Socket yourself? 

You can send/recv UDP packets outside of Pion DTLS. That way it doesn't care where the packets are coming from or going.

**Comment by evangelme** [comment]
@Sean-Der 
thank you for your response. yes it is possible but not in my country. in my country we are under censorship so i have to use these protocols and if i use DTLS as well they block it. the only way to use these is to send the data with 1 IP and receive  with another IP so this way the DPI dose not detect it.

**Comment by Sean-Der** [comment]
Tell me if I can do anything else! Happy to make examples or code changes if you need 

thanks for using Pion!
