### ISSUE TITLE
Release 1.4.0

### ISSUE THREAD

**Issue by daenney** [pion/dtls#80]
There's been a number of changes since the current 1.3.x series that I believe warrant a release and a bump to the minor version.

* [x] AES-CCM #46 
* [x] PSK support #66
  * [x] TLS_PSK_WITH_AES_128_CCM_8 #76
  * [x] TLS_PSK_WITH_AES_128_GCM_SHA256 #78 

I'd also like to get #79 in.

Anything else of note or importance to get done for 1.4?

**Comment by Sean-Der** [comment]
This sounds great to me! Really excited to see this working out for everyone that needs PSK (for all these IoT devices)

We need to really start a Twitter account and start writing blog posts etc... I am not involved with the IoT/security community at all so I don't even know where to post/announce this stuff. I just know WebRTC/video

**Comment by daenney** [comment]
Twitter is relatively easy; you can create a Pion Twitter account and then using https://tweetdeck.twitter.com/ you can give people the ability to post as Pion through their own account (so no need to share account passwords). The `#golang` and `#iot` tags ought to do the trick for some exposure there. There's also plenty of bots that'll auto-tweet on blog post releases as long as you have an RSS feed.

**Comment by Sean-Der** [comment]
@daenney only issue is that twitter.com/pion and twitter.com/pions is taken :/

It looks like they aren't fond of turning over inactive accounts either. We could do something like `pion-github` but seems a bit sad.

**Comment by daenney** [comment]
pionrtc is free, which wouldn't be half bad.

**Comment by Sean-Der** [comment]
Hey sorry for the delay @daenney 

I got https://twitter.com/_pion and make you an admin! I will post on Slack if anyone else is interested. I will work on setting up the account more now. But feel free to cut a release/post where ever you want about it :) 

I am sure people are sick of seeing me pushing Pion everywhere :p

**Comment by daenney** [comment]
What delay? I believe both you and I are supposed to be on vacation :stuck_out_tongue:. Is there anything specific we do for releases or just push a new tag?

**Comment by daenney** [comment]
I've just pushed the v1.4.0 tag. If there's anything I missed as part of the release process do let me know. I'll close this now.

**Comment by daenney** [comment]
The tweet about it is here: https://twitter.com/_pion/status/1150453486561169409 in case anyone wants to boost it.
